name: CI
on: [push]
jobs:
  ts-check:
    name: Check Typescript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i
      - name: Run TS Check
        run: npm run typecheck
